/** 图标注册表 —— 数据层用字符串键引用,统一在此映射 */
import type { Component } from 'vue'
import { INK_ICONS } from './inkIcons'
import {
  Axe,
  Bell,
  Bird,
  BookOpen,
  Castle,
  CircleDot,
  Cloud,
  Crown,
  Download,
  Droplets,
  Fish,
  FlaskConical,
  Footprints,
  Ghost,
  Hammer,
  Home,
  Leaf,
  Link,
  Lock,
  Moon,
  PawPrint,
  RefreshCw,
  Scroll,
  Shield,
  ShieldCheck,
  Shirt,
  Skull,
  Sparkles,
  Sprout,
  Star,
  Sunset,
  Sword,
  Trash2,
  Trees,
  Unlock,
  Upload,
  User,
  Wand,
  Watch,
  Waves,
  X,
  Zap,
  Umbrella
} from 'lucide-vue-next'

export const ICONS: Record<string, Component> = {
  axe: Axe,
  bell: Bell,
  bird: Bird,
  book: BookOpen,
  castle: Castle,
  'circle-dot': CircleDot,
  cloud: Cloud,
  crown: Crown,
  download: Download,
  droplets: Droplets,
  fish: Fish,
  flask: FlaskConical,
  footprints: Footprints,
  ghost: Ghost,
  hammer: Hammer,
  home: Home,
  leaf: Leaf,
  link: Link,
  lock: Lock,
  moon: Moon,
  paw: PawPrint,
  refresh: RefreshCw,
  scroll: Scroll,
  shield: Shield,
  /** 镇压中的地界签用的是 'shield-check',此前没登记,于是静静显示成一枚星芒 */
  'shield-check': ShieldCheck,
  shirt: Shirt,
  skull: Skull,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sunset: Sunset,
  sword: Sword,
  trash: Trash2,
  trees: Trees,
  unlock: Unlock,
  upload: Upload,
  user: User,
  wand: Wand,
  watch: Watch,
  waves: Waves,
  x: X,
  zap: Zap,
  umbrella: Umbrella,
  /*
   * 水墨那八枚(底部导航五项 + 顶栏三项)在末尾铺进来,与上面的 lucide 图标同网格、
   * 同线宽、同圆头圆角 —— 换的是形与笔,不是语言。同名键不在这里重复登记:
   * 一个图标名只许有一个来源(详见 inkIcons.ts)。
   */
  ...INK_ICONS
}

export function iconOf(name: string): Component {
  return ICONS[name] ?? Sparkles
}
